
services:
  ml-backend:
    container_name: SAM2BigImg
    image: humansignal/ml-backend:v0
    build:
      context: .
      args:
        TEST_ENV: False

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [ gpu ]

    environment:
      # specify these parameters if you want to use basic auth for the model server
      - BASIC_AUTH_USER=
      - BASIC_AUTH_PASS=
      # set the log level for the model server
      - LOG_LEVEL=DEBUG
      # any other parameters that you want to pass to the model server
      - ANY=PARAMETER
      # specify the number of workers and threads for the model server
      - WORKERS=1
      - THREADS=8
      # specify the model directory (likely you don't need to change this)
      - MODEL_DIR=/data/models
      # specify device
      - DEVICE=cuda  # or 'cpu' (coming soon)
      # SAM2 model config and checkpoint
      - MODEL_CONFIG=configs/sam2.1/sam2.1_hiera_l.yaml
      - MODEL_CHECKPOINT=sam2.1_hiera_large.pt

      # Specify the Label Studio URL and API key to access uploaded, local storage and cloud storage files.
      - LABEL_STUDIO_URL=https://ichthyolith.whoi.edu
      - LABEL_STUDIO_API_KEY=b7fc46b3c2c391dd81411010459e8df9feb7b95a
     # - LABEL_STUDIO_URL=https://labelstudio.brick.whoi.edu
     # - LABEL_STUDIO_API_KEY=36a67ff6c9fd0e0082f570162683e447ae2623fe
    ports:
      - "22202:9090"
    volumes:
      - "./data/server:/data"
      - "./data/cache:/cache"
